### ISSUE TITLE
How to detect motion?

### ISSUE THREAD

**Issue by swa72** [dermotduffy/hass-motioneye#136]
Hi,

I'm currently stuggeling to enable motion detection with the integration. So far, I have both "Home Assistant Community Add-on: motionEye" and this "Add-on MotionEye" integration installed (confusing names, btw).  I added a bunch of entities to lovelace
```  
  - binary_sensor.livingroom_file_stored
  - binary_sensor.livingroom_motion
  - switch.livingroom_motion_detection
  - switch.livingroom_movies
  - switch.livingroom_still_images
```
motionEye has motion detection enabled and shows detected motion nicely with a square. I can turn detection on and off in lovelace. Motion Notifications is configured to call a web hook

`http://homeassistant-eth.local:8123/api/motioneye/device/fdefe9c73721d9319c69131c474ba711/motion_detected?camera_id=%t&changed_pixels=%D&despeckle_labels=%Q&event=%v&fps=%{fps}&frame_number=%q&height=%h&host=%{host}&motion_center_x=%K&motion_center_y=%L&motion_height=%J&motion_version=%{ver}&motion_width=%i&noise_level=%N&threshold=%o&width=%w&src=hass-motioneye`

However, `binary_sensor.livingroom_motion` never changes and if I listen to events `(motioneye.motion_detected)` using HA's Developer Tools it never fires.

Any idea, what I am missing?

**Comment by dermotduffy** [comment]
>  So far, I have both "Home Assistant Community Add-on: motionEye" and this "Add-on MotionEye" integration 

If you are referring to this repo, this is not an addon, this is an integration. Terminology:

* Add-on: A wrapper that allows other (often unrelated) applications to run on HomeAssistant Operating System via docker containers.
* Integrations: Code that allows Home Assistant Core to control/communicate with to other systems/services (which can include talking to addons).

> Motion Notifications is configured to call a web hook

Does that address `homeassistant-eth` look right to you?

Can you confirm if you're really using this custom integration, or the motionEye integration that is built into Home Assistant? (They are different).

**Comment by dermotduffy** [comment]
[Insufficient information to debug]
