### ISSUE TITLE
Motion Entity

### ISSUE THREAD

**Issue by weitheng** [dermotduffy/hass-motioneye#55]
I have enabled motion detection in the add on, but the integration does not seem to include binary sensor for the motion detection. Do I need to enable web hook in the add on, if so, where should the web hook point to?

**Comment by dermotduffy** [comment]
Are you using the (basic) built-in Core version of the motionEye integration, or this custom component via HACS? The basic (by default) Core integration does not yet support motion detection, as I'm in the process of moving over the functionality from this custom_component which has many more features.

If you're not using the custom component, here are the [installation instructions](https://github.com/dermotduffy/hass-motioneye#installation) . That page also includes details of the generated events, and the binary_sensor. The webhooks are automatically set.

**Comment by weitheng** [comment]
Ahh I see, so that's why. I am using the built-in Core version at the moment. 

Just wondering will there be any difference in functionality in the future between this custom_component and the core version, or will they be eventually the same?

**Comment by dermotduffy** [comment]
See ["Long-term intention" in the documentation](https://github.com/dermotduffy/hass-motioneye#long-term-intention).

**Comment by weitheng** [comment]
Sorry should have seen that. 
Looks like blazing fast progress is being made, motion detection is already ready to be implemented just waiting for reviews. Thank you for this amazing integration!

**Comment by broyuken** [comment]
I'm using the one from hacs and I have a binary sensor created, but the camera entity can show me walking into the room but the motion sensor never triggers. I'm using default settings on the camera outside of changing the name and resolution.
