### ISSUE TITLE
Audio in recordings

### ISSUE THREAD

**Issue by broyuken** [dermotduffy/hass-motioneye#56]
**Is your feature request related to a problem? Please describe.**
There is no audio in motioneye recordings or live streams

**Describe the solution you'd like**
There to be audio in motioneye recordings or live streams

**Describe alternatives you've considered**

**Additional context**
I use Wyze v2 Cameras with the RTSP firmware but there doesn't seem to be any audio in either the motioneye dashboard or in HA.

**Comment by dermotduffy** [comment]
This is not related to the integration, nor even to motionEye. The underlying system [motion](https://motion-project.github.io/) does not support audio. As per the maintainers, this is [unlikely to change for the foreseeable future](https://github.com/Motion-Project/motion/wiki/FAQ#q--does--will-motion-support-audio-recording).

If audio is required for your usecase, I would recommend a different tool entirely ([example](https://blakeblackshear.github.io/frigate/)).

Thanks for the issue, good luck.
