### ISSUE TITLE
Entity Camera. and Services not working

### ISSUE THREAD

**Issue by rul3zz** [dermotduffy/hass-motioneye#64]
motionEye Version | 0.42.1
Motion Version | 4.2.2
OS Version | Ubuntu 20.04

I tried this new integration with my motioneye, switch and  sensors seem to work fine, except for the camera. entity , is unavailable.
![Screenshot_3](https://user-images.githubusercontent.com/17640550/121808435-c5a44e80-cc58-11eb-8035-b2b6fe19db52.png)

 
![Screenshot_5](https://user-images.githubusercontent.com/17640550/121808606-888c8c00-cc59-11eb-8f71-8c509de78891.png)

I also tried to use motion service but there's no effects.. 

![Screenshot_4](https://user-images.githubusercontent.com/17640550/121808543-46634a80-cc59-11eb-9778-4d665e541c81.png)

any suggestion?

**Comment by dermotduffy** [comment]
For the camera stream, the video streaming must be enabled (i.e. the "Camera1 Video Streaming" switch that is off in your screenshot).

For the snapshot service, images need to be turned on (see the "Camera1 Still Images" switch), and the "Capture mode" should be set to "Manual" in the motionEye UI.

Try making those changes? (Please close the bug if you get it working -- thanks!)

**Comment by rul3zz** [comment]
> For the camera stream, the video streaming must be enabled (i.e. the "Camera1 Video Streaming" switch that is off in your screenshot).
> 
> For the snapshot service, images need to be turned on (see the "Camera1 Still Images" switch), and the "Capture mode" should be set to "Manual" in the motionEye UI.
> 
> Try making those changes? (Please close the bug if you get it working -- thanks!)

Oh that's correct, sorry, now snapshott work with still image and capture manual.
And what about motionEye: Action service record_start / record_stop? testing it  but does not record (snapshott service is working)

![Screenshot_6](https://user-images.githubusercontent.com/17640550/121867717-8af5f100-cd00-11eb-8972-de5b8d968e67.png)

![Screenshot_1](https://user-images.githubusercontent.com/17640550/121867724-8c271e00-cd00-11eb-9612-cd1ccc6da48b.png)

And my motion settings

![Screenshot_2](https://user-images.githubusercontent.com/17640550/121867745-921cff00-cd00-11eb-8837-c18eeabdec54.png)

**Comment by dermotduffy** [comment]
Please see [this note](https://github.com/dermotduffy/hass-motioneye#motioneyeaction) in the documentation:

> Note: As of 2021-04-11 the record_start and record_stop action are not implemented in motionEye itself and thus do not function in this integration ([relevant code](https://github.com/ccrisan/motioneye/blob/dev/motioneye/handlers.py#L1741)).

**Comment by rul3zz** [comment]
Tnx Dermotduffy
