### ISSUE TITLE
Option to explicitly set the callback URL for webhooks

### ISSUE THREAD

**Issue by CantankerousBullMoose** [dermotduffy/hass-motioneye#87]
**Is your feature request related to a problem? Please describe.**
I run Home Assistant with two network interfaces: one for connecting to an isolated IoT network, and another one for the outside world. It would be really hard for Home Assistant or this component to guess which one of those is the right one for MotionEye to send API calls to. In fact the call to homeassistant.helpers.network.get_url actually returns a third address which doesn't even exist on my system, but that's another problem. The point is, **webhooks configured in MotionEye for things like Motion Notification don't point to the correct address of my Home Assistant instance.**

**Describe the solution you'd like**
An option to manually configure the address that will be used in webhooks from config file or UI

**Describe alternatives you've considered**
Getting get_url fixed in core might help some, but because of the multiple network interfaces it's probably not a complete solution. Only one of the interfaces can be used to dial out to the MotionEye instance, so there might be some way to use that to determine which of the multiple interfaces is the correct one, but as mentioned above, automatically working out the correct interface and address seems like more of a "nice to have" feature.

**Additional context**

**Comment by dermotduffy** [comment]
How about this strategy
   * Have HA set the webhooks once.
   * Ensure the "Overwrite unrecognized webhooks" option is disabled in the integration (the default)
   * Open your motionEye UI and manually edit the webhooks for your cameras to the appropriate address, removing the 'src=hass-motioneye' parameter.

With that configuration, you'll have manually tweaked the callback URL and hass-motioneye will never overwrite them.

Would that work?

It's definitely a bit of manual work, but really this FR is asking to add a manual way to set webhooks URL -- and the motionEye UI literally offers that already, so might be best just relying on that? Put another way, why should the motionEye integration offer a way to set an arbitrary webhook callback to _somewhere_ else? Feels like the core of the issue may be that you are unable to have `get_url` actually return something that works for you?

**Comment by CantankerousBullMoose** [comment]
This is definitely a good workaround to get me up and running right now. I wasn't sure if that hex string in the middle of the URL was static, but it seems like it is.

Arguably saving manual work is the whole point of the webhooks piece in the first place. After all, there have been successful implementations of a home assistant sensor for motion where people used the motionEye UI to set up vanilla Home Assistant API calls to update a variable. 

I guess it also depends on how comfortable you are making the rest of that callback URL a truly public API. If this component is always going to update webhooks and nothing outside this component has much reason to use the motionEye API endpoint in HomeAssistant, you can change the format of that URL and know that you're going to update the webhooks in motionEye itself to match. If I take this as a long term solution, you'll break my setup any time you change the URL format.

**Comment by dermotduffy** [comment]
Yes, the hex string is generated once when the integration is first enabled and saved. It will only change if the motionEye server is removed from the integration (or the integration reinstall, for example). The only mandatory part of the webhook is the path part -- all of the query parameters (after '?') can be changed/removed and everything should continue to work (it's just that the pieces of data you remove won't be available in the generated events). In all, the odds of the webhook format changing in such a way that it breaks the integration seem quite low.  And even if that did happen, you'd just enable "Overwrite unrecognized webhooks" and then repeat the manual tweak.

I agree that setting the webhook in the first place is saving manual work, but the difference to me is that it is saving work for "all users  of the integration" vs "all users of the integration who want the webhook to call back into HomeAssistant, but for whom the `get_url` returns an invalid value`. My feeling is that this second set is extremely small, i.e. this feature would not be used by any appreciable portion of the audience. What do you think?

**Comment by CantankerousBullMoose** [comment]
Supposing that, either through a configuration change on my part or an update to core, `get_url` does return the "right" value, I don't think it's clear which of my two NICs would to refer to. As far as the audience goes, keep in mind that the general audience for the integration is not "people who have IP cameras and a computer", but rather "people who take the time to set up motionEye and Home Assistant instead of using off-the-shelf cloud-based solutions from Google, Amazon, etc." I suspect that among the second group, a security best practice like segmented networks where IoT devices and cameras are isolated from the internet is probably much more popular than it is with the public at large.

The other big usecase is running inside a Docker container where the externally available IP for home assistant doesn't match the one home assistant "sees". I think the internal vs external url configuration in home assistant is used to mitigate some of these types of issues, but for that to work here I think you would have to expose those flags in the call to `get_url` as configuration settings.

**Comment by CantankerousBullMoose** [comment]
Switching from `get_url` to `async_get_source_ip` (`(https://github.com/home-assistant/core/blob/c3a509bdd88a0f0bc3c0d58d11d293a71af26874/homeassistant/components/network/util.py#L144)`) would solve the two NICs issue without complicating things for other people, I think.

**Comment by dermotduffy** [comment]
The migration of this repository to Home Assistant Core is now complete, so this feature request or PR should be targeted there instead of this custom repository. Thanks for your understanding.
